server:
  port: 8080

datasource:
  driverClassName: ${DB_DRIVER}
  url: ${DB_URL}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  sql-dialect: postgresql

cache:
  view:
    initialCapacity: 100
    maximumSize: 800
    expireAfterAccess: 8
    expirationAfterAccessUnits: HOURS
  form:
    initialCapacity: 100
    maximumSize: 800
    expireAfterAccess: 8
    expirationAfterAccessUnits: HOURS
  query:
    initialCapacity: 100
    maximumSize: 800
    expireAfterAccess: 8
    expirationAfterAccessUnits: HOURS

springdoc:
  swagger-ui:
    enabled: true