server:
  port: 8081

spring:
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
